export const FETCH_WEATHERDATA_START = 'FETCH_WEATHERDATA_START';
export const FETCH_WEATHERDATA_SUCCESS = 'FETCH_WEATHERDATA_SUCCESS';
export const FETCH_WEATHERDATA_FAIL = 'FETCH_WEATHERDATA_FAIL';
export const SET_DATA='SET_DATA';